apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.slaveNodeName_1}}-nodeport #nodeport service name
    namespace: {{ .Values.slaveNodeNamespace_1}}
    labels:
        app: {{ .Values.slaveNodeName_1}}-nodeport
spec:
    type: NodePort #表明这个service类型是nodeport
    ports:
        - port: 10000  #network port
          nodePort: {{ .Values.slaveNodeNodeportnetworkPort_1}}
          name: network
        - port: 10001  #rpc port
          nodePort: {{ .Values.slaveNodeNodeportrpcPort_1}}
          name: rpc
    selector:
        app: {{ .Values.slaveNodeName_1}}   # should match the selector.matchLabels  for StatefulSet which is 'app: ${slaveNodeName}'