apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.masterNodeName}}-nodeport #nodeport service name
    namespace: {{ .Values.masterNodeNamespace}}
    labels:
        app: {{ .Values.masterNodeName}}-nodeport
spec:
    type: NodePort
    ports:
        - port: 10000  #network port
          nodePort: {{ .Values.masterNodeNodeportnetworkPort}} # The best way should be determined by system but here we just fix it
          name: network
        - port: 10001  #rpc port
          nodePort: {{ .Values.masterNodeNodeportrpcPort}}  # The best way should be determined by system but here we just fix it
          name: rpc
    selector:
        app: {{ .Values.masterNodeName}}   # should match the selector.matchLabels  for StatefulSet which is 'app: {{ .Values.masterNodeName}}'