apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.masterNodeName}} # headless service name, will be used to be part of the DNS name
    namespace: {{ .Values.masterNodeNamespace}}
    labels:
        app: {{ .Values.masterNodeName}}
spec:
    clusterIP: None  #headless service
    ports:
        - name: network #network port
          port: 10000 #in really system end user can give this value dynamically
          targetPort: 10000 # The best way should be determined by system but here we just fix it
        - name: rpc #rpc port
          port: 10001   #in really system end user can give this value dynamically
          targetPort: 10001 # The best way should be determined by system but here we just fix it
    selector:
        app: {{ .Values.masterNodeName}} # should match the selector.matchLabels  for StatefulSet  which is 'app: ${masterNodeName}