apiVersion: v1
kind: Service
metadata:
  name: multichainclient-nodeport
  namespace: {{ .Values.multichainClientNamespace}}
spec:
  type: NodePort
  selector:
    app: multichainclient
  ports:
    - port: 9081
      targetPort: 9081
      nodePort: {{ .Values.multichainClientNodeport}}